version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[security]"
      include: scope
    labels:
      - "npm"
      - "dependencies"
      - "server"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
    reviewers:
      - "CPU-commits"
    target-branch: "master"
    versioning-strategy: "auto"